= kapture-localization:  toolbox
:sectnums:
:sectnumlevels: 1
:toc: macro
:toclevels: 2

toc::[]

== Overview

kapture-localization is a **toolbox** in which you will find implementations for various localization related algorithms.
It strongly relies on the https://github.com/naver/kapture[kapture] package for data representation and manipulation.

The localization algorithms aims to do:

 . **mapping**,
 . **localization** and
 . **benchmarking** (only image retrieval).

It works on Ubuntu, Windows and MacOS.

== structure

The directories are organised as follow:

----
├── kapture_localization/  # package (library)
├── pipeline/              # main programs scheduling all steps needed in localization pipelines
├── samples/               # some sample data
├── tests/                 # unit tests
└── tools/                 # sub programs involved in the pipeline
----


The __kapture-localization__ toolbox provides both :

 - Python *package* (`kapture_localization/`),
 - Python *executable scripts* (`pipeline/` & `tools/`).

There is basically 3 pipelines, for:

 . mapping,
 . localization and
 . image retrieval benchmark (global sfm, local sfm, pose approximation).


== Installation

You can either install using docker, pip or from the source code manually.
Basically, you will need python (>=3.6) and Colmap (>=3.6) to be installed, and then you
can

[source,bash]
----
pip install kapture-localization
----

See link:doc/installation.adoc[] for more details.

== Tutorial

See the link:doc/tutorial.adoc[doc/tutorial] for a short introduction to:

 - mapping pipeline
 - localization pipeline
 - image retrieval benchmark (global sfm, local sfm, pose approximation)

 
== Contributing

There are many ways to contribute to the __kapture-localization__ project:

* provide feedback and suggestions of improvements,
* submit bug reports in the project bug tracker,
* implement a feature or bug-fix for an outstanding issue,
* provide scripts to create data in kapture format (e.g. local/global feature extraction),
* propose a new feature and implement it.

// TODO individual page for kapture-localization ?
If you wish to contribute, please refer to the  link:https://github.com/naver/kapture/blob/master/CONTRIBUTING.adoc[CONTRIBUTING] page.

== License
Software license is detailed in the link:LICENSE[LICENSE] file.
