= kapture-localization / pipeline

Here you'll find example of usage for the different pipeline scripts.
For a more detailed explanation, please refer to link:../doc/tutorial.adoc[doc/tutorial].

Before you try out the following commands, make sure :

 - You have local features and global features saved in the recommended dataset structure
before you run the pipeline scripts in this folder.
Refer to the section **prepare data** of link:../doc/tutorial.adoc[doc/tutorial] page.

 - Windows users should take care of extra installation steps.
Refer to link:../doc/installation.adoc[doc/installation]

== kapture_pipeline_mapping.py

This script computes

- the image pairs from global features,
- the corresponding matches,
- the geometric verification and finally
- the colmap map.

typical call:
[source,bash]
----
kapture_pipeline_mapping.py
    -i my_dataset/mapping \
    -kpt my_dataset/local_features/r2d2_WASF-N8_20k/keypoints \
    -desc my_dataset/local_features/r2d2_WASF-N8_20k/descriptors \
    -gfeat my_dataset/global_features/AP-GeM-LM18/global_features \
    -matches my_dataset/local_features/r2d2_WASF-N8_20k/NN_no_gv/matches \
    -matches-gv my_dataset/local_features/r2d2_WASF-N8_20k/NN_colmap_gv/matches \
    --colmap-map my_dataset/colmap-sfm/r2d2_WASF-N8_20k/AP-GeM-LM18_top20 # lfeat_type / map_pairs \
    --topk 20
----

== kapture_pipeline_localize.py

This script computes

 - the image pairs from global features,
 - the corresponding matches,
 - the geometric verification and finally
 - localization of images against an existing colmap map.

The parameters passed to `colmap image_registrator` are described in
link:https://europe.naverlabs.com/research/publications/robust-image-retrieval-based-visual-localization-using-kapture/[].

[source,text]
----
config=0 : []
config=1 : ['--Mapper.ba_refine_focal_length', '0',
            '--Mapper.ba_refine_principal_point', '0',
            '--Mapper.ba_refine_extra_params', '0']
config=2 : ['--Mapper.ba_refine_focal_length', '0',
            '--Mapper.ba_refine_principal_point', '0',
            '--Mapper.ba_refine_extra_params', '0',
            '--Mapper.min_num_matches', '4',
            '--Mapper.init_min_num_inliers', '4',
            '--Mapper.abs_pose_min_num_inliers', '4',
            '--Mapper.abs_pose_min_inlier_ratio', '0.05',
            '--Mapper.ba_local_max_num_iterations', '50',
            '--Mapper.abs_pose_max_error', '20',
            '--Mapper.filter_max_reproj_error', '12'],
config=3 : ['--Mapper.ba_refine_focal_length', '1',
            '--Mapper.ba_refine_principal_point', '0',
            '--Mapper.ba_refine_extra_params', '0',
            '--Mapper.min_num_matches', '4',
            '--Mapper.init_min_num_inliers', '4',
            '--Mapper.abs_pose_min_num_inliers', '4',
            '--Mapper.abs_pose_min_inlier_ratio', '0.05',
            '--Mapper.ba_local_max_num_iterations', '50',
            '--Mapper.abs_pose_max_error', '20',
            '--Mapper.filter_max_reproj_error', '12']
----

Typical call:

[source,bash]
----
kapture_pipeline_localize.py
    -i my_dataset/mapping \
    --query my_dataset/query \
    --merge-path my_dataset/map_plus_query # optional, providing it will avoid recomputing it \
    -kpt my_dataset/local_features/r2d2_WASF-N8_20k/keypoints \
    -desc my_dataset/local_features/r2d2_WASF-N8_20k/descriptors \
    -gfeat my_dataset/global_features/AP-GeM-LM18/global_features \
    -matches my_dataset/local_features/r2d2_WASF-N8_20k/NN_no_gv/matches \
    -matches-gv my_dataset/local_features/r2d2_WASF-N8_20k/NN_colmap_gv/matches \
    --colmap-map my_dataset/colmap-sfm/r2d2_WASF-N8_20k/AP-GeM-LM18_top20 # lfeat_type / map_pairs \
    -o my_dataset/colmap-localization/r2d2_WASF-N8_20k/AP-GeM-LM18_top20/AP-GeM-LM18_top20/ # lfeat_type / map_pairs / query_pairs / \
    --topk 20 \
    --config 2
# add --prepend_cam when the dataset is RobotCar_Seasons or RobotCar Seasons v2
----


== kapture_pipeline_image_retrieval_benchmark.py

Produces results from "Benchmarking Image Retrieval for Visual Localization".
It adds two more steps compared to localize.py :

 - pose approximation (EWB, BDI, CSI) and
 - local sfm.

You can run it the same way:

[source,bash]
----
kapture_pipeline_image_retrieval_benchmark.py
    -i my_dataset/mapping \
    --query my_dataset/query \
    --merge-path my_dataset/map_plus_query  # optional, providing it will avoid recomputing it \
    -kpt my_dataset/local_features/r2d2_WASF-N8_20k/keypoints \
    -desc my_dataset/local_features/r2d2_WASF-N8_20k/descriptors \
    -gfeat my_dataset/global_features/AP-GeM-LM18/global_features \
    -matches my_dataset/local_features/r2d2_WASF-N8_20k/NN_no_gv/matches \
    -matches-gv my_dataset/local_features/r2d2_WASF-N8_20k/NN_colmap_gv/matches \
    --colmap-map my_dataset/colmap-sfm/r2d2_WASF-N8_20k/AP-GeM-LM18_top20 # lfeat_type / map_pairs \
    -o my_dataset/ir-benchmark/r2d2_WASF-N8_20k/AP-GeM-LM18_top20/AP-GeM-LM18_top20/ # lfeat_type / map_pairs / query_pairs \
    --topk 20 \
    --config 2

# add --prepend_cam when the dataset is RobotCar_Seasons or RobotCar Seasons v2
----
