= kapture-localization / installation
:sectnums:
:sectnumlevels: 1
:toc:
:toclevels: 2

You can either install using docker, pip or from the source code manually.

== Docker: the fast way

We provide a docker image, you can run it:

[source,bash]
----
docker run --runtime=nvidia # benefit the GPU acceleration \
    -it --rm # Automatically remove the container when it exits \
    --volume <my_data>:<my_data> # give access to your data on your machine \
    kapture/kapture-localization
----

You can also build your own docker image as follow  :

[source,bash]
----
git clone https://github.com/naver/kapture-localization.git
cd kapture-localization
docker build --tag kapture/kapture-localization .
----

== pip: the simple way

Requirements:

 - python 3.6 + python3-pip
 - colmap (optional)

=== linux (Ubuntu 18.04 LTS)

In a terminal (e.g. __bash__), run:

[source,bash]
----
# install requirements
sudo apt-get install -y python3.6 python3-pip colmap
# install kapture-localization
python3 -m pip install kapture-localization
----

=== Windows and MacOS

.Requirements

Download and install the latest 3.6 release from https://www.python.org/downloads/ for your machine.

NOTE: **For windows user**: when running the installer, tick `Add Python 3.6 to PATH`,
then `customize`, make sure __pip__, __Python test suite__ and __py launcher__ are installed.

Get the latest __colmap__ binaries from https://github.com/colmap/colmap/releases.

Finally, in a terminal (e.g. __powershell__), run:
[source,bash]
----
pip3 install kapture-localization
----

NOTE: **For windows user**: __kapture-localization__ uses symlinks to optimize transfer operations. But symbolic links are not fully
supported on __windows__ platform, and may lead to permission errors. If you encounter that kind of errors,
please consider using __copy__ or __skip__ as transfer mode.

== from source: for developers

NOTE: __kapture-localization__ can also work as a stand-alone, without being installed.

In addition to package (<<pip: the simple way>>) requirements, you need to install:

 - __git__.

Optionally, for documentation, you will also need to install

- __pandoc__,
- __asciidoctor__.

=== linux (Ubuntu 18.04 LTS)

In a terminal, do:

[source,bash]
----
# install requirements
sudo apt-get install -y git python3.6 python3-pip colmap
# install optionnal requirements
sudo apt-get install -y pandoc asciidoctor
# clone source repository
git clone https://github.com/naver/kapture-localization.git
cd kapture-localization
# check everything is fine
python3 -m unittest discover -s tests
# install
python3 setup.py build install
----

=== Windows and MacOS

Download and install :

 - __git__ from https://git-scm.com/download/[git-scm.com].

Optionally, for documentation, download and install

 - __pandoc__ from https://github.com/jgm/pandoc/releases/tag/2.9.2.1[github.com/jgm/pandoc],
 - __asciidoctor__ from https://asciidoctor.org/[asciidoctor.org].

Then, in a command prompt (cmd or powershell) run:

[source,bash]
----
# clone source repository
git clone https://github.com/naver/kapture-localization.git
cd kapture-localization
# check everything is fine
python -m unittest discover -s tests
# install
python setup.py build install
----
