= kapture-localization / installation
:sectnums:
:sectnumlevels: 1
:toc:
:toclevels: 2

You can install this toolbox using docker, pip or manually from the source code.

== Docker: the fast way

We provide a docker image that can be run like this:

[source,bash]
----
docker run --runtime=nvidia # benefit from the GPU acceleration \
    -it --rm # automatically remove the container when it exits \
    --volume <my_data>:<my_data> # give access to your data on your machine \
    kapture/kapture-localization
----

You can also build your own docker image as follow:

[source,bash]
----
git clone https://github.com/naver/kapture-localization.git
cd kapture-localization
docker build --tag kapture/kapture-localization .
----

== pip: the simple way

Requirements:

 - python >= 3.6 + python3-pip
 - COLMAP >= 3.6

=== linux (Ubuntu 18.04 LTS)

kapture-localization requires a recent version of COLMAP (>=3.6).
Unfortunately, `apt-get` in Ubuntu 18.04 will install COLMAP 3.4.
A solution is **to install COLMAP from source**. You will find instructions of how to do that in the link:../Dockerfile[Dockerfile] and on the https://colmap.github.io/install.html[COLMAP website].

Then, in a terminal (e.g. __bash__), run:

[source,bash]
----
# install requirements
# make sure you have COLMAP 3.6 (see above instructions)
sudo apt-get install -y python3.6 python3-pip
# install kapture-localization
python3 -m pip install kapture-localization
----

=== Windows and MacOS

Download and install the latest python 3.6 release from https://www.python.org/downloads/ for your machine.

NOTE: **For windows user**: when running the installer, tick `Add Python 3.6 to PATH`,
then `customize`, make sure __pip__, __Python test suite__ and __py launcher__ are installed.

Get the latest __COLMAP__ binaries (>=3.6) from https://github.com/colmap/colmap/releases.

Finally, in a terminal (e.g. __powershell__), run:
[source,bash]
----
pip3 install kapture-localization
----

=== For Windows users

.Symlinks
__kapture-localization__ uses symlinks to optimize file transfer operations.
However, symbolic links are not fully supported on __windows__ platforms and may lead to permission errors.
For most kapture scripts, you can use __copy__ or __skip__ as transfer mode in order to avoid this issue.
For the pipeline scripts, you cannot avoid the use of symlinks and will have to run them as administrator.

.Long Paths

__kapture__ matches folder contains file with long names. When running the pipelines, you will most likely hit the 260 character filename limit. On Windows 10 version 1607 and later, you can enable long paths by running the following command in an elevated powershell prompt. More information https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell[here]

[source,bash]
----
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
----


.Python file extension
You should have the file extension `.py` associated to the python 3.6 executable:

`Windows > Choose default apps by file type > .py > python`

.COLMAP path
You must use `colmap.bat`. If the __COLMAP__ path is not available from your `%PATH%`
environment variable, you must provide it to kapture tools through the parameter `-colmap`,
e.g. `-colmap C:/Workspace/dev/colmap/colmap.bat`.


== From source: for developers

NOTE: __kapture-localization__ can also work as a stand-alone, without being installed.

In addition to the package (<<pip: the simple way>>) requirements, you need to install __git__,
and optionally (for documentation), __pandoc__ and __asciidoctor__.

When you install __kapture-localization__ from source, you should also install __kapture__ from source, as the most recent changes in __kapture-localization__ might use code from __kapture__ which are not part of a release or pushed to pip yet.

=== Linux (Ubuntu 18.04 LTS)

In a terminal, do:

[source,bash]
----
# install developer requirements
sudo apt-get install -y git pandoc asciidoctor
# clone source repository
git clone https://github.com/naver/kapture-localization.git
cd kapture-localization
# check everything is fine
python3 -m unittest discover -s tests
# install
python3 setup.py build install
----

=== Windows and MacOS

Download and install :

 - __git__ from https://git-scm.com/download/[git-scm.com].
 - [optional]  __pandoc__ from https://github.com/jgm/pandoc/releases/tag/2.9.2.1[github.com/jgm/pandoc],
 - [optional] __asciidoctor__ from https://asciidoctor.org/[asciidoctor.org].

Then, in a command prompt (cmd or powershell) run:

[source,bash]
----
# clone source repository
git clone https://github.com/naver/kapture-localization.git
cd kapture-localization
# check everything is fine
python -m unittest discover -s tests
# install
python setup.py build install
----
